import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import List

from backend.config import GMAIL_ADDRESS, GMAIL_APP_PASSWORD

logger = logging.getLogger(__name__)

RECIPIENT = "deepanvishal@gmail.com"

_RISK_COLORS = {"High": "#dc2626", "Medium": "#d97706", "Low": "#16a34a"}
_ROW_COLORS = {
    "high": "#fee2e2",
    "medium": "#fef3c7",
    "low": "#dcfce7",
}


def _score_row_color(score: int) -> str:
    if score > 66:
        return _ROW_COLORS["high"]
    if score > 33:
        return _ROW_COLORS["medium"]
    return _ROW_COLORS["low"]


def send_risk_email(
    contract_name: str,
    supplier_name: str,
    risk_score: int,
    risk_level: str,
    recommendation: str,
    summary: list | str,
    flagged_clauses: List[dict],
) -> bool:
    risk_color = _RISK_COLORS.get(risk_level, "#6b7280")

    if isinstance(summary, list):
        bullets_html = "".join(f"<li style='margin-bottom:6px;'>{h}</li>" for h in summary)
    else:
        bullets_html = "".join(
            f"<li style='margin-bottom:6px;'>{line.lstrip('• ').strip()}</li>"
            for line in str(summary).split("\n")
            if line.strip()
        )

    clause_rows = ""
    for clause in flagged_clauses:
        score = int(clause.get("score", 0))
        clause_rows += f"""
        <tr style="background-color:{_score_row_color(score)};">
            <td style="padding:8px;border:1px solid #e5e7eb;">{clause.get('type', '').replace('_', ' ').title()}</td>
            <td style="padding:8px;border:1px solid #e5e7eb;text-align:center;font-weight:bold;">{score}/100</td>
            <td style="padding:8px;border:1px solid #e5e7eb;">{clause.get('reason', '')}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html><body style="font-family:Arial,sans-serif;max-width:820px;margin:0 auto;padding:20px;color:#1e293b;">
<div style="background:#1e293b;color:white;padding:24px;border-radius:8px 8px 0 0;">
    <h1 style="margin:0;font-size:22px;font-weight:700;">&#9888; Contract Risk Alert</h1>
    <p style="margin:6px 0 0;opacity:.8;font-size:15px;">{contract_name}</p>
</div>
<div style="border:1px solid #e5e7eb;border-top:none;padding:24px;border-radius:0 0 8px 8px;">
    <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:20px;">
        <tr>
            <td width="33%" style="text-align:center;padding:16px;background:#f8fafc;border-radius:8px;">
                <div style="font-size:52px;font-weight:900;color:{risk_color};line-height:1;">{risk_score}</div>
                <div style="color:#64748b;font-size:13px;margin-top:4px;">Risk Score</div>
            </td>
            <td width="4%"></td>
            <td width="33%" style="text-align:center;padding:16px;background:#f8fafc;border-radius:8px;">
                <div style="font-size:38px;font-weight:800;color:{risk_color};line-height:1;">{risk_level}</div>
                <div style="color:#64748b;font-size:13px;margin-top:4px;">Risk Level</div>
            </td>
            <td width="4%"></td>
            <td width="33%" style="text-align:center;padding:16px;background:#f8fafc;border-radius:8px;">
                <div style="font-size:28px;font-weight:800;color:#1e293b;line-height:1;">{recommendation}</div>
                <div style="color:#64748b;font-size:13px;margin-top:4px;">Recommendation</div>
            </td>
        </tr>
    </table>
    <p style="margin:0 0 16px;"><strong>Supplier:</strong> {supplier_name or 'N/A'}</p>
    <h3 style="margin:0 0 10px;font-size:16px;">Key Highlights</h3>
    <ul style="margin:0 0 20px;padding-left:20px;">{bullets_html}</ul>
    <h3 style="margin:0 0 10px;font-size:16px;">Flagged Clauses</h3>
    <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
        <thead>
            <tr style="background:#f1f5f9;">
                <th style="padding:10px 8px;border:1px solid #e5e7eb;text-align:left;font-size:13px;">Clause Type</th>
                <th style="padding:10px 8px;border:1px solid #e5e7eb;text-align:center;font-size:13px;width:80px;">Score</th>
                <th style="padding:10px 8px;border:1px solid #e5e7eb;text-align:left;font-size:13px;">Risk Reason</th>
            </tr>
        </thead>
        <tbody>{clause_rows}</tbody>
    </table>
</div>
<p style="color:#94a3b8;font-size:11px;margin-top:12px;text-align:center;">
    Generated by Contract Risk Agent &bull; deepanvishal@gmail.com
</p>
</body></html>"""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Contract Risk Alert: {contract_name} — {risk_level}"
    msg["From"] = GMAIL_ADDRESS
    msg["To"] = RECIPIENT
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.ehlo()
            server.starttls()
            server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_ADDRESS, RECIPIENT, msg.as_string())
        logger.info("Email sent for contract '%s' (%s)", contract_name, risk_level)
        return True
    except Exception as exc:
        logger.error("Failed to send email for '%s': %s", contract_name, exc)
        return False
